version: '3.9'

services:
  api:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      - FLASK_ENV=development
